version: "3.5"
services:
  python:
    image: audiodude/0bt
    container_name: 0bt
    volumes:
      - /opt/data:/var/www/data/up
      - /opt/app/db:/app/db
      - /opt/app/config:/app/config
    ports:
      - 7321:7321

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - USER=transmission
      - PASS="${TRANSMISSION_PW}"
    volumes:
      - /opt/transmission/config:/config
      - /opt/data:/downloads
      - /opt/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  tracker:
    image: lednerb/opentracker-docker
    container_name: tracker
    ports:
      - 5555:6969
      - 5555:6969/udp
    restart: unless-stopped

networks:
  default:
    name: 0bt
